services:
  SERVICE_NAME:
    build: .
    container_name: ${SITE_NAME}
    restart: always
    volumes:
      - ./app:/app/public
    environment:
      - "SERVER_NAME=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SITE_NAME}.rule=Host(`${SITE_URL}`)"
      - "traefik.http.routers.${SITE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SITE_NAME}.tls.certresolver=le"
      - "traefik.http.services.${SITE_NAME}.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
