services:
  SERVICE_NAME:
    build:
      context: .
      args:
        GO_VERSION: ${GO_VERSION:-1.24}
    container_name: ${SITE_NAME}
    restart: RESTART_POLICY
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV:-production}
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: 'CPU_LIMIT'
          memory: 'MEMORY_LIMIT'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
